# -*- coding: utf-8 -*-
"""LH_CD_KELLY_PATRICIA_LOPES_SILVA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1j83OWGbdPsEB5X7hWCKD5CnY7FvaD3Aq

# **Indicium** - Desafio Cientista de Dados - *Kelly Silva*
"""

#importando a biblioteca pandas
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/Datasets/cars_train.csv", encoding='utf-16le', sep='\t')

# Visualizando as 5 primeiras linhas
df.head()

# Total de linhas e colunas
df.shape

# Apenas as colunas da planilha
df.columns

# Quantidade de linhas e colunas
df.dtypes

# As ultimas linhas do conjunto de dados.
df.tail()

# Retorna informações estatitica do banco de dados
df.describe()

# Filtro
df["preco"].unique()

# Consultando linhas com valores faltantes
df.isnull().sum()

